### ISSUE TITLE
[worker] Support `.yaml` Declarations

### ISSUE THREAD

**Issue by joshjms** [joshjms/jjudge#3]
To increase flexibility of the code execution, we can declare our steps in a similar to Github Actions `yaml` file manner. Since we do not aim to use shared volumes to persist filesystem, we want to run all steps in a single pod - this includes preparation, compilation, and execution.

My idea of how the `.yaml` file should look like:

```yaml
files:
  - name: "a.cpp"
    content: |
      #include <iostream>
      using namespace std;

      int main() {
          cout << "Hello, World!" << endl;
          return 0;
      }
steps:
  - name: "compile"
    commands:
      - "g++ a.cpp -o a"
    error:
      message: "compile error"
  - name: "run"
    commands:
      - "./a"
```
